// NEW FEED
export const BEGIN_GET_NEW_FEED = 'BEGIN_GET_NEW_FEED';
export const GET_NEW_FEED_SUCCESS = 'GET_NEW_FEED_SUCCESS';
export const GET_NEW_FEED_ERROR = 'GET_NEW_FEED_ERROR';
// USER PROFILE
export const BEGIN_GET_USER_PROFILE = 'BEGIN_GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROGRESS_SUCCESS = 'GET_USER_PROGRESS_SUCCESS';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';
// LOGIN
export const INITIAL_LOGIN = 'INITIAL_LOGIN';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_DATA_LOGIN = 'UPDATE_DATA_LOGIN';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
// PRODUCT
export const BEGIN_GET_FULL_INFO_ABOUT_ONE_POST = 'BEGIN_GET_FULL_INFO_ABOUT_ONE_POST';
export const GET_FULL_INFO_ABOUT_ONE_POST_SUCCESS = 'GET_FULL_INTRO_ABOUT_ONE_POST_SUCCESS';
export const GET_COMMENTS_POST_SUCCESS = 'GET_COMMENTS_POST_SUCCESS';
export const GET_FULL_INFO_ABOUT_ONE_POST_ERROR = 'GET_FULL_INFO_ABOUT_ONE_POST_ERROR';
// SEARCH
export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
// REGISTER
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
//UPDATE PROFILE
export const BEGIN_UPDATE_PROFILE = "BEGIN_UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
// COURSE
export const BEGIN_GET_COURSE = "BEGIN_GET_COURSE";
export const GET_COURSE_SUCCESS = "BEGIN_GET_COURSE";
export const GET_COURSE_ERROR = "BEGIN_GET_COURSE";
// NOTIFICATION
export const BEGIN_GET_NOTIFICATION = "BEGIN_GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";