// NEW FEED
export const BEGIN_GET_NEW_FEED = 'BEGIN_GET_NEW_FEED';
export const GET_NEW_FEED_SUCCESS = 'GET_NEW_FEED_SUCCESS';
export const GET_NEW_FEED_ERROR = 'GET_NEW_FEED_ERROR';
export const BEGIN_REFRESH_NEWFEED = 'BEGIN_REFRESH_NEWFEED';
export const REFRESH_NEWFEED_SUCCESS = 'REFRESH_NEWFEED_SUCCESS';
export const REFRESH_NEWFEED_ERROR = 'REFRESH_NEWFEED_ERROR';
export const SELECTED_USER_PROFILE_NEWFEED = 'SELECTED_USER_PROFILE_NEWFEED';
export const CHANGE_THE_VIEW = 'CHANGE_THE_VIEW';
// USER PROFILE
export const BEGIN_GET_USER_PROFILE = 'BEGIN_GET_USER_PROFILE';
export const BEGIN_GET_USER_PROGRESS = 'BEGIN_GET_USER_PROGRESS';
export const BEGIN_GET_USER_PRODUCTS = 'BEGIN_GET_USER_PRODUCTS';
export const BEGIN_GET_USER_SIDE_NAV = 'BEGIN_GET_USER_SIDE_NAV';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROGRESS_SUCCESS = 'GET_USER_PROGRESS_SUCCESS';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_SIDE_NAV_SUCCESS = 'GET_USER_SIDE_NAV_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';
export const GET_USER_PROGRESS_ERROR = 'GET_USER_PROGRESS_ERROR';
export const GET_USER_PRODUCTS_ERROR = 'GET_USER_PRODUCTS_ERROR';
export const GET_USER_SIDE_NAV_ERROR = 'GET_USER_SIDE_NAV_ERROR';
// MY ACCOUNT
export const BEGIN_GET_MYACCOUNT_PROFILE = 'BEGIN_GET_MYACCOUNT_PROFILE';
export const BEGIN_GET_MYACCOUNT_PROGRESS = 'BEGIN_GET_MYACCOUNT_PROGRESS';
export const BEGIN_GET_MYACCOUNT_PRODUCTS = 'BEGIN_GET_MYACCOUNT_PRODUCTS';
export const GET_MYACCOUNT_PROFILE_SUCCESS = 'GET_MYACCOUNT_PROFILE_SUCCESS';
export const GET_MYACCOUNT_PROGRESS_SUCCESS = 'GET_MYACCOUNT_PROGRESS_SUCCESS';
export const GET_MYACCOUNT_PRODUCTS_SUCCESS = 'GET_MYACCOUNT_PRODUCTS_SUCCESS';
export const GET_MYACCOUNT_PROFILE_ERROR = 'GET_MYACCOUNT_PROFILE_ERROR';
export const GET_MYACCOUNT_PROGRESS_ERROR = 'GET_MYACCOUNT_PROGRESS_ERROR';
export const GET_MYACCOUNT_PRODUCTS_ERROR = 'GET_MYACCOUNT_PRODUCTS_ERROR';
// LOGIN
export const INITIAL_LOGIN = 'INITIAL_LOGIN';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_DATA_LOGIN = 'UPDATE_DATA_LOGIN';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN  = 'LOGIN';
// PRODUCT
export const BEGIN_GET_FULL_INFO_ABOUT_ONE_POST = 'BEGIN_GET_FULL_INFO_ABOUT_ONE_POST';
export const GET_FULL_INFO_ABOUT_ONE_POST_SUCCESS = 'GET_FULL_INTRO_ABOUT_ONE_POST_SUCCESS';
export const GET_COMMENTS_POST_SUCCESS = 'GET_COMMENTS_POST_SUCCESS';
export const GET_POST_LIKER_SUCCESS = 'GET_POST_LIKER_SUCCESS';
export const GET_FULL_INFO_ABOUT_ONE_POST_ERROR = 'GET_FULL_INFO_ABOUT_ONE_POST_ERROR';
export const BEGIN_POST_COMMENT = 'BEGIN_POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';
// SEARCH
export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const CHANGE_VALUE_SEARCH = 'CHANGE_VALUE_SEARCH';
// REGISTER
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// UPDATE PROFILE
export const BEGIN_UPDATE_PROFILE = "BEGIN_UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
// COURSE
export const BEGIN_GET_COURSE = "BEGIN_GET_COURSE";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_ERROR = "GET_COURSE_ERROR";
// CURRICULUM
export const BEGIN_GET_CURRICULUM = "BEGIN_GET_CURRICULUM";
export const GET_CURRICULUM_SUCCESS = "GET_CURRICULUM_SUCCESS";
// COURSE INFORMATION
export const BEGIN_GET_COURSE_INFORMATION = "BEGIN_GET_COURSE_INFORMATION";
export const GET_COURSE_INFORMATION_SUCCESS = "GET_COURSE_INFORMATION_SUCCESS";
export const GET_COURSE_INFORMATION_ERROR = "GET_COURSE_INFORMATION_ERROR";
// LEARN REGISTER
export const BEGIN_LEARN_REGISTER = "BEGIN_LEARN_REGISTER";
export const LEARN_REGISTER_SUCCESS = "LEARN_REGISTER_SUCCESS";
export const LEARN_REGISTER_ERROR = "LEARN_REGISTER_ERROR";
// NOTIFICATION
export const BEGIN_GET_NOTIFICATION = "BEGIN_GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";
export const REFRESH_NOTIFICATION_SUCCESS = "REFRESH_NOTIFICATION_SUCCESS";
export const REFRESH_NOTIFICATION_ERROR = "REFRESH_NOTIFICATION_ERROR";
export const BEGIN_REFRESH_NOTIFICATION = "BEGIN_REFRESH_NOTIFICATION";
// REPORT POST
export const BEGIN_REPORT_POST = "BEGIN_REPORT_POST";
export const REPORT_POST_SUCCESS = "REPORT_POST_SUCCESS";
export const REPORT_POST_ERROR = "REPORT_POST_ERROR";
// CHANGE AVATAR
export const BEGIN_CHANGE_AVATAR = "BEGIN_CHANGE_AVATAR";
// GROUP
export const BEGIN_GET_GROUP_TOPICS = 'BEGIN_GET_GROUP_TOPICS';
export const BEGIN_GET_GROUP_PRODUCTS = 'BEGIN_GET_GROUP_PRODUCTS';
export const BEGIN_GET_GROUP_MEMBER = 'BEGIN_GET_GROUP_MEMBER';
export const GET_GROUP_TOPICS_SUCCESS = 'GET_GROUP_TOPICS_SUCCESS';
export const GET_GROUP_PRODUCTS_SUCCESS = 'GET_GROUP_PRODUCTS_SUCCESS';
export const GET_GROUP_MEMBER_SUCCESS = 'GET_GROUP_MEMBER_SUCCESS';
export const GET_GROUP_TOPICS_ERROR = 'GET_GROUP_TOPICS_ERROR';
export const GET_GROUP_PRODUCTS_ERROR = 'GET_GROUP_PRODUCTS_ERROR';
export const GET_GROUP_MEMBER_ERROR = 'GET_GROUP_MEMBER_ERROR';
// TOPIC
export const BEGIN_GET_TOPIC = 'BEGIN_GET_TOPIC';
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
export const BEGIN_GET_PRODUCTS_IN_TOPIC = 'BEGIN_GET_PRODUCTS_IN_TOPIC';
export const GET_PRODUCTS_IN_TOPIC_SUCCESS = 'GET_PRODUCTS_IN_TOPIC_SUCCESS';
// SIDE NAV
export const BEGIN_GET_SIDE_NAV = 'BEGIN_GET_SIDE_NAV';
export const GET_SIDE_NAV_SUCCESS = 'GET_SIDE_NAV_SUCCESS';
export const GET_SIDE_NAV_ERROR = 'GET_SIDE_NAV_ERROR';
//FEEDBACK
export const BEGIN_FEEDBACK = 'BEGIN_FEEDBACK';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
// get DetailNoti
export const BEGIN_GET_DETAILNOTI = "BEGIN_GET_DETAILNOTI";
export const GET_DETAILNOTI_SUCCESS = "GET_DETAILNOTI_SUCCESS";
export const GET_DETAILNOTI_ERROR = "GET_DETAILNOTI_ERROR";

//get bases
export const BEGIN_GET_LIST_BASE = "BEGIN_GET_LIST_BASE";
export const GET_LIST_BASE_SUCCESS = "GET_LIST_BASE_SUCCESS";
export const GET_LIST_BASE_ERROR = "GET_LIST_BASE_ERROR";
// get more bases
export const BEGIN_GET_MORE_LIST_BASE = "BEGIN_GET_MORE_LIST_BASE";
export const GET_MORE_LIST_BASE_SUCCESS = "GET_MORE_LIST_BASE_SUCCESS";
// refresh bases
export const BEGIN_REFRESH_LIST_BASE = "BEGIN_REFRESH_LIST_BASE";
export const GET_REFRESH_BASE_SUCCESS = "GET_REFRESH_BASE_SUCCESS";
//
// get all bases
export const BEGIN_GET_ALL_LIST_BASE = "BEGIN_GET_ALL_LIST_BASE";
export const GET_ALL_LIST_BASE_SUCCESS = "GET_ALL_LIST_BASE_SUCCESS";