// NEW FEED
export const BEGIN_GET_NEW_FEED = 'BEGIN_GET_NEW_FEED';
export const GET_NEW_FEED_SUCCESS = 'GET_NEW_FEED_SUCCESS';
export const GET_NEW_FEED_ERROR = 'GET_NEW_FEED_ERROR';
export const BEGIN_REFRESH_NEWFEED = 'BEGIN_REFRESH_NEWFEED';
export const REFRESH_NEWFEED_SUCCESS = 'REFRESH_NEWFEED_SUCCESS';
export const REFRESH_NEWFEED_ERROR = 'REFRESH_NEWFEED_ERROR';
export const SELECTED_USER_PROFILE_NEWFEED = 'SELECTED_USER_PROFILE_NEWFEED';
export const CHANGE_THE_VIEW = 'CHANGE_THE_VIEW';
// USER PROFILE
export const BEGIN_GET_USER_PROFILE = 'BEGIN_GET_USER_PROFILE';
export const BEGIN_GET_USER_PROGRESS = 'BEGIN_GET_USER_PROGRESS';
export const BEGIN_GET_USER_PRODUCTS = 'BEGIN_GET_USER_PRODUCTS';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROGRESS_SUCCESS = 'GET_USER_PROGRESS_SUCCESS';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';
export const GET_USER_PROGRESS_ERROR = 'GET_USER_PROGRESS_ERROR';
export const GET_USER_PRODUCTS_ERROR = 'GET_USER_PRODUCTS_ERROR';
// MY ACCOUNT
export const BEGIN_GET_MYACCOUNT_PROFILE = 'BEGIN_GET_MYACCOUNT_PROFILE';
export const BEGIN_GET_MYACCOUNT_PROGRESS = 'BEGIN_GET_MYACCOUNT_PROGRESS';
export const BEGIN_GET_MYACCOUNT_PRODUCTS = 'BEGIN_GET_MYACCOUNT_PRODUCTS';
export const GET_MYACCOUNT_PROFILE_SUCCESS = 'GET_MYACCOUNT_PROFILE_SUCCESS';
export const GET_MYACCOUNT_PROGRESS_SUCCESS = 'GET_MYACCOUNT_PROGRESS_SUCCESS';
export const GET_MYACCOUNT_PRODUCTS_SUCCESS = 'GET_MYACCOUNT_PRODUCTS_SUCCESS';
export const GET_MYACCOUNT_PROFILE_ERROR = 'GET_MYACCOUNT_PROFILE_ERROR';
export const GET_MYACCOUNT_PROGRESS_ERROR = 'GET_MYACCOUNT_PROGRESS_ERROR';
export const GET_MYACCOUNT_PRODUCTS_ERROR = 'GET_MYACCOUNT_PRODUCTS_ERROR';

// LOGIN
export const INITIAL_LOGIN = 'INITIAL_LOGIN';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_DATA_LOGIN = 'UPDATE_DATA_LOGIN';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const LOGOUT = 'LOGOUT';
// PRODUCT
export const BEGIN_GET_FULL_INFO_ABOUT_ONE_POST = 'BEGIN_GET_FULL_INFO_ABOUT_ONE_POST';
export const GET_FULL_INFO_ABOUT_ONE_POST_SUCCESS = 'GET_FULL_INTRO_ABOUT_ONE_POST_SUCCESS';
export const GET_COMMENTS_POST_SUCCESS = 'GET_COMMENTS_POST_SUCCESS';
export const GET_POST_LIKER_SUCCESS = 'GET_POST_LIKER_SUCCESS';
export const GET_FULL_INFO_ABOUT_ONE_POST_ERROR = 'GET_FULL_INFO_ABOUT_ONE_POST_ERROR';
export const BEGIN_POST_COMMENT = 'BEGIN_POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
// SEARCH
export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const CHANGE_VALUE_SEARCH = 'CHANGE_VALUE_SEARCH';
// REGISTER
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
//UPDATE PROFILE
export const BEGIN_UPDATE_PROFILE = "BEGIN_UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
// COURSE
export const BEGIN_GET_COURSE = "BEGIN_GET_COURSE";
export const GET_COURSE_SUCCESS = "BEGIN_GET_COURSE";
export const GET_COURSE_ERROR = "BEGIN_GET_COURSE";
// NOTIFICATION
export const BEGIN_GET_NOTIFICATION = "BEGIN_GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";
// REPORT POST
export const BEGIN_REPORT_POST = "BEGIN_REPORT_POST";
export const REPORT_POST_SUCCESS = "REPORT_POST_SUCCESS";
export const REPORT_POST_ERROR = "REPORT_POST_ERROR";
// CHANGE AVATAR
export const BEGIN_CHANGE_AVATAR = "BEGIN_CHANGE_AVATAR";
// GROUP
export const BEGIN_GET_GROUP_TOPICS = 'BEGIN_GET_GROUP_TOPICS';
export const BEGIN_GET_GROUP_PRODUCTS = 'BEGIN_GET_GROUP_PRODUCTS';
export const BEGIN_GET_GROUP_MEMBER = 'BEGIN_GET_GROUP_MEMBER';
export const GET_GROUP_TOPICS_SUCCESS = 'GET_GROUP_TOPICS_SUCCESS';
export const GET_GROUP_PRODUCTS_SUCCESS = 'GET_GROUP_PRODUCTS_SUCCESS';
export const GET_GROUP_MEMBER_SUCCESS = 'GET_GROUP_MEMBER_SUCCESS';
export const GET_GROUP_TOPICS_ERROR = 'GET_GROUP_TOPICS_ERROR';
export const GET_GROUP_PRODUCTS_ERROR = 'GET_GROUP_PRODUCTS_ERROR';
export const GET_GROUP_MEMBER_ERROR = 'GET_GROUP_MEMBER_ERROR';

